### ISSUE TITLE
Multi-arch docker images

### ISSUE THREAD

**Issue by petersem** [cgnetwork/trailarr#7]
Enhancement: Provide additional docker images for arm32/64

**Comment by NiNiyas** [comment]
Any update on this issue?

**Comment by trueChazza** [comment]
Hi, thanks for your query.

This is next on my list to work on. I will provide a progress update within the week.

**Comment by trueChazza** [comment]
There is now a multi architecture image supporting:
* linux/amd64
* linux/arm64
* linux/arm/v7

To give it a spin, use the tag `cgnetwork/trailarr:multi-arch`

**Comment by NiNiyas** [comment]
I am still getting `standard_init_linux.go:228: exec user process caused: exec format error`

My docker-compose.yml:
```
  trailarr:
    container_name: Trailarr
    image: cgnetwork/trailarr:multi-arch
    volumes:
      - .trailers:/trailers
    ports:
      - 8081:8080
  ```
```
 $ uname -a
Linux odin 5.4.0-1047-raspi #52-Ubuntu SMP PREEMPT Wed Nov 24 08:16:38 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```
